name: mlops-pipeline
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
env:
  AWS_REGION: "us-east-1"
  DEV_AWS_ACCOUNT_ID: "382625484581"
  DEV_AWS_IAM_ROLE_NAME: "Github-acition-oicd" 
  GH_TOKEN: ${{ github.token }}       
permissions:
  id-token: write
  contents: read
  actions: write
  issues: write  
jobs:
  mlops-build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  
      - name: Upgrade PIP
        run: |
          sudo apt-get update
          sudo apt-get install build-essential python3-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip setuptools wheel
          wget https://files.pythonhosted.org/packages/19/87/8c8d9a0a91a5eb4de47a1f3ef4172d32e2c20164f77cbf2879054b5e4c67/PyYAML-5.3.1-cp38-cp38-manylinux1_x86_64.whl
          pip install PyYAML-5.3.1-cp38-cp38-manylinux1_x86_64.whl
          pip install -r requirements.txt --use-feature=2020-resolver    
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::357171621133:role/github-oidc-role
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Execute SageMaker variable script
        run: |
          python scripts/scripts.py
